# Project: breakout
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = core.o main.o $(RES)
LINKOBJ  = core.o main.o $(RES)
LIBS =  -L"C:/mine/DevCpp/lib" -lalleg  
INCS =  -I"C:/mine/DevCpp/include" 
CXXINCS =  -I"C:/mine/DevCpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/mine/DevCpp/include/c++/3.4.2/backward"  -I"C:/mine/DevCpp/include/c++/3.4.2/mingw32"  -I"C:/mine/DevCpp/include/c++/3.4.2"  -I"C:/mine/DevCpp/include" 
BIN  = breakout.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before breakout.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "breakout.exe" $(LIBS)

core.o: core.cpp
	$(CPP) -c core.cpp -o core.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
